{{- if and .Values.grafana.persistence.enabled (not .Values.grafana.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.grafana.persistence.storageClassName }}
  storageClassName: {{ .Values.grafana.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
